### Register
POST http://localhost/stock-exchange-api/public/api/auth/register
Content-Type: application/json

{
    "role": "buyer",
    "name": "API Test User",
    "email": "api-test@example.com",
    "password": "TestPassword123!",
    "phone": "0912345678"
}


### Login
POST http://localhost/stock-exchange-api/public/api/auth/login
Content-Type: application/json

{
    "email": "api-test@example.com",
    "password": "TestPassword123!"
}


### Logout
POST http://localhost/stock-exchange-api/public/api/auth/logout
Authorization: Bearer 60f346ec0488ab7f865b359e0d5650a56be39adf802399fde02e004cdff45e02

### Get authenticated user
GET http://localhost/stock-exchange-api/public/api/auth/me
Authorization: Bearer 414840578b74eca4251a8e848a1baeb57e7ab2b6d530b2b34493bbd8aa921eed